<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOxhkN62\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOxhkN62/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerOxhkN62.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerOxhkN62\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerOxhkN62\App_KernelProdContainer([
    'container.build_hash' => 'OxhkN62',
    'container.build_id' => 'e513efee',
    'container.build_time' => 1583456961,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOxhkN62');
