<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTDpBxAS\App_KernelProddDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTDpBxAS/App_KernelProddDebugContainer.php') {
    touch(__DIR__.'/ContainerTDpBxAS.legacy');

    return;
}

if (!\class_exists(App_KernelProddDebugContainer::class, false)) {
    \class_alias(\ContainerTDpBxAS\App_KernelProddDebugContainer::class, App_KernelProddDebugContainer::class, false);
}

return new \ContainerTDpBxAS\App_KernelProddDebugContainer([
    'container.build_hash' => 'TDpBxAS',
    'container.build_id' => '134ad663',
    'container.build_time' => 1583456803,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTDpBxAS');
