<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'post_list' => [[], ['_controller' => 'App\\Controller\\PostController::index'], [], [['text', '/']], [], []],
    'new_post' => [[], ['_controller' => 'App\\Controller\\PostController::new'], [], [['text', '/post/new']], [], []],
    'relevant_post' => [['tag'], ['_controller' => 'App\\Controller\\PostController::relevant'], ['tag' => '\\d+'], [['variable', '/', '\\d+', 'tag', true], ['text', '/post/tag']], [], []],
    'update_post' => [['id'], ['_controller' => 'App\\Controller\\PostController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/post/update']], [], []],
    'app_post_delete' => [['id'], ['_controller' => 'App\\Controller\\PostController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/post/delete']], [], []],
    'post_post' => [['id'], ['_controller' => 'App\\Controller\\PostController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/post']], [], []],
    'relevant' => [['tag'], ['_controller' => 'App\\Controller\\PostController::relevant'], [], [['variable', '/', '[^/]++', 'tag', true], ['text', '/post/tag']], [], []],
];
