<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNOaxRHt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNOaxRHt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNOaxRHt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNOaxRHt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNOaxRHt\App_KernelDevDebugContainer([
    'container.build_hash' => 'NOaxRHt',
    'container.build_id' => '448decdc',
    'container.build_time' => 1583457216,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNOaxRHt');
