<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'post_list' => [[], ['_controller' => 'App\\Controller\\PostController::index'], [], [['text', '/']], [], []],
    'new_post' => [[], ['_controller' => 'App\\Controller\\PostController::new'], [], [['text', '/post/new']], [], []],
    'update_post' => [['id'], ['_controller' => 'App\\Controller\\PostController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/post/update']], [], []],
    'app_post_delete' => [['id'], ['_controller' => 'App\\Controller\\PostController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/post/delete']], [], []],
    'relevant_post' => [['tag'], ['_controller' => 'App\\Controller\\PostController::relevant'], [], [['variable', '/', '[^/]++', 'tag', true], ['text', '/post/relevant']], [], []],
    'post_post' => [['id'], ['_controller' => 'App\\Controller\\PostController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/post']], [], []],
    'relevant' => [['tag'], ['_controller' => 'App\\Controller\\PostController::relevant'], [], [['variable', '/', '[^/]++', 'tag', true], ['text', '/post/tag']], [], []],
];
